
name: docker

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Validate Docker builds
    # don't push to registry, just validate build
    runs-on: ubuntu-latest
    steps:
      - name: Build Python
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.Python
      - name: Build R
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.R
