name: gh-pages

on:
  push:
    paths-ignore:
      - '**/README.*md'
  pull_request:
    paths-ignore:
      - '**/README.*md'
  workflow_dispatch:

jobs:
    gh-pages-deploy:
      name: Build and deploy
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1
          with:
            version: 12.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Set homepage - ${{ github.repository }}
          # replace default values from the fork in `package.json`
          run: |
            IFS="/" read -a a <<< ${{ github.repository }}
            sed -i "s/tgve/${a[0]}/" package.json
            sed -i "s/app/${a[1]}/" package.json
            # debug
            cat package.json
        - name: Install dependencies
          run: yarn install  # CRA uses yarn by default

        - name: Build
          run: yarn run build
          env:
            CI: false
            REACT_APP_DEFAULT_URL: https://raw.githubusercontent.com/tgve/example-data/main/casualties.csv
            REACT_APP_MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_KEY}}

        - name: Deploy
          if: github.ref == 'refs/heads/release'
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout --orphan gh-pages
            git --work-tree build add --all
            git --work-tree build commit -m 'Deploy'
            git push origin HEAD:gh-pages --force

