name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
      # error jest-diff@26.6.2: The engine "node" is incompatible with this module. 
      # Expected version ">= 10.14.2". Got "8.17.0"
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn install && Test
      run: |
        yarn install
        yarn run test
      env:
        CI: true
